// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ApplyAndRestart():Promise<void>;

export function CheckForUpdates(arg1:string):Promise<models.UpdateStatus>;

export function CreateItem(arg1:string,arg2:number,arg3:string):Promise<models.Item>;

export function DownloadUpdate():Promise<models.UpdateStatus>;

export function Greet(arg1:string):Promise<string>;

export function ListItems():Promise<Array<models.Item>>;

export function SetCurrentVersion(arg1:string):Promise<void>;

export function UpdateItem(arg1:number,arg2:string,arg3:number,arg4:string):Promise<models.Item>;

export function WithdrawQuantity(arg1:number,arg2:number,arg3:string):Promise<models.Item>;
