// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateItem'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListItems() {
  return window['go']['main']['App']['ListItems']();
}

export function UpdateItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateItem'](arg1, arg2, arg3, arg4);
}

export function WithdrawQuantity(arg1, arg2, arg3) {
  return window['go']['main']['App']['WithdrawQuantity'](arg1, arg2, arg3);
}
