name: release-windows

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to attach asset to (e.g. v1.0.2)
        required: true

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build (Wails)
        run: wails build -clean

      - name: Rename artifact (generic filename)
        shell: bash
        run: |
          mkdir -p build/windows
          cp build/bin/goods_wails_app.exe build/windows/goods_wails_app_windows_amd64.exe

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name || inputs.tag }}
          files: build/windows/goods_wails_app_windows_amd64.exe
          fail_on_unmatched_files: true
